////////////////////////////////////////////////////////////////////////////////
Copyright (c) 2012, THE BOARD OF TRUSTEES OF THE LELAND STANFORD JUNIOR UNIVERSITY
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
   Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
   Neither the name of the STANFORD UNIVERSITY nor the names of its contributors
   may be used to endorse or promote products derived from this software without
   specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////

A Cyclades Service Engine Nyxlet/service for XSL processing

== Basic Features

* Basic XSL processing via XSLT

== Overview

* This product is provided under the terms of the BSD license, please see "LICENSE" for more information

* Although this product is used in production enviroments, it is currently being transitioned to an Open Source Software project. That being said, there will be aspects of this project that will need refinement as its maturing process as an Open Source Software project progresses (documentation, APIs, bugs etc...). We are looking forward to the feedback and contributions that will improve this product for the OSS community.

* More documentation will be viewable online shortly. In the meantime, you will need to generate the current documentation from this source distribution. Instructions on how to do this will be included below as part of the _Build And Deployment Instructions (*nix platforms)_ section

* The terms "Service" and "Nyxlet" are synonymous with respect to Cyclades SOA. A Nyxlet is simply a service module that is pluggable into the Cyclades Service Engine. We will offer a set of utility Nyxlets to build and/or deploy shortly (like this one). Each will exist as an independent repository. Developers will also be encouraged to offer their Nyxlets to the community. 

= Build And Deployment Instructions (*nix platforms)

== Overview

This document describes the steps involved for Service (Nyxlet) developers and end users to build and deploy this Nyxlet. You must have *Gradle* installed to build. You must additionally have a running Cyclades Engine instance if a deployment is to be done. After we are done, you will have built and deployed this Nyxlet. Please follow the instructions below.

== Build The Nyxlet

. Install Gradle (if you do not already have it): http://www.gradle.org

. Install Tomcat (if you do not already have it): http://tomcat.apache.org (We're running on Tomcat 7) This could be a standard installation on any host, local or remote

. Download and install (extract) a stable version of this repository (the Nyxlet Source Distribution) within a directory of choice (example: "/cycladessoa/nyxlets")
	.. https://github.com/cycladessoa/nyxlet-xsl/archive/v1.0.0.5.zip (We'll assume the extracted directory is "/cycladessoa/nyxlets/xsl" for our purposes)

. From within the directory "/cycladessoa/nyxlets/xsl" run the command _gradle clean build_

. The Cyclades Service Engine binary distribution exists within a Nyxlet's workspace _build/libs_ directory after a successful build. This will be in the form of a "cyclades*.war" file. Simply copy this file to your Tomcat installation's "webapps" directory and be sure to name it "cyclades.war".

. Restart Tomcat and verify the installation
	.. http://localhost:8080/cyclades (Core Cyclades Service Engine status page should be displayed without error)
	.. http://localhost:8080/cyclades?action=help (Help page displays without error)

. Deploy the Nyxlet to a running Cyclades Engine Instance
	.. If running on localhost, simply run the command _gradle deploy_ from within the "/cycladessoa/nyxlets/xsl" directory, by default localhost will be the deployment target
	.. If running on another machine, or set of machines, modify your gradle.properties file prior to running the command _gradle deploy_
		... Modify the "base_engine_url_list" property in "/cycladessoa/nyxlets/xsl/gradle.properties". This can be a comma separated list if deploying to multiple nodes

.Example non-localhost configuration for two machines
----
base_engine_url_list={"url":"http://server1.mycompany.org:8080/cyclades","password":""},{"url":"http://server2.mycompany.org:8080/cyclades","password":""}
----

* You should be able to verify your Nyxlet is loaded by going to the following URL in your browser: http://localhost:8080/cyclades?action=loaded
* You should be able to view all available actions on your Nyxlet by going to the following URL in your browser: http://localhost:8080/cyclades/my_first_nyxlet?data-type=xml&action=listactions

== Generate Current Documentation

. Install Gradle (if you do not already have it): http://www.gradle.org

. Download and install "AsciiDoc" (if you do not already have it): http://www.methods.co.nz/asciidoc

. From within the base directory of your Nyxlet Source Distribution, run the command _./doc_gen.sh . generated_docs_ If you have not previously downloaded and installed the Nyxlet Source Distribution, please do the following before generating the documentation:
	.. Download and install (extract) a stable version of this repository (the Nyxlet Source Distribution) within a directory of choice (example: "/cycladessoa/nyxlets")
        	... https://github.com/cycladessoa/nyxlet-xsl/archive/v1.0.0.5.zip (We'll assume the extracted directory is "/cycladessoa/nyxlets/xsl" for our purposes)

. Open the file "/cycladessoa/nyxlets/xsl/generated_docs/index.html" in a browser window

[NOTE]
Please keep in mind this is an initial version of the documentation and we will be working on improvements throughout this project.
