////////////////////////////////////////////////////////////////////////////////
Copyright (c) 2012, THE BOARD OF TRUSTEES OF THE LELAND STANFORD JUNIOR UNIVERSITY
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
   Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
   Neither the name of the STANFORD UNIVERSITY nor the names of its contributors
   may be used to endorse or promote products derived from this software without
   specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////

= Service Profile: xsl
:toc:

== Document Version
1.0

== Intent
The intent of this document is to provide an overview and meta data for the discovery of this service and its capabilities. This document should be comprehensible to all stakeholders. This document may also be indexed and used to aid in service discovery. An access route can be utilized via tha Service Registry home page.

== Name
xsl

== Purpose

=== Short
XSL functionality

=== Detailed
XSL functionality

== Service Model 
Utility

== Tags
xml, xsl, transformation, filter, xslt

== Owner
TBD

== Status
Done

== Deployment Overview

=== Service Handle
xsl

=== Protocol/Interface Classification
* synchronous
* STROMA compliant (Transport Protocol Agnostic)
* HTTP adapter is included with default installation

=== Dependencies On Other Services
None

=== Deployment Location
(TBD: We may benefit by having this on all installations)

== Service Capabilities

.Capabilities/Actions
[options="header"]
|=========================================================
|Action				|Purpose						|Tags					|Status
|transform			|Provide pipeline XSL transformations			|xsl, xslt, xml 			|Complete
|xslt				|Provide pipeline XSL transformations via filter	|xsl, xslt, xml, filter                 |Complete
|=========================================================

== Modifications To This Document

[options="header"]
|=========================================================
|Author			|Date		|Version	|Details
|Tom Angelopoulos	|3/23/2012	|1.0		|Document Creation
|=========================================================
